### Project Group ###
projectGroup=com.loopers
### Project dependency versions ###
kotlinVersion=2.3.21
### Plugin dependency versions ###
ktLintPluginVersion=12.1.2
ktLintVersion=1.0.1
### Spring dependency versions ###
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
springCloudDependenciesVersion=2025.1.2
### Library versions ###
springDocOpenApiVersion=3.0.3
springMockkVersion=4.0.2
mockitoVersion=5.14.0
instancioJUnitVersion=5.0.2
slackAppenderVersion=1.6.1
testcontainers.version=1.21.4
queryDslVersion=7.6
kotlin.daemon.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m
